- name: ensure database is created
  postgresql_db: name={{DATABASE_NAME}}

- name: ensure user has access to database
  postgresql_user: db={{DATABASE_NAME}} name={{DATABASE_USER}} password={{DATABASE_PASSWORD}} priv=ALL

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{DATABASE_USER}} role_attr_flags=NOSUPERUSER,CREATEDB

- name: ensure no other user can access the database
  postgresql_privs: db={{DATABASE_NAME}} role=PUBLIC type=database priv=ALL state=absent