language: python
python:
  - "3.6"

before_install:
  - sudo pip install ansible

install:
  - pip install -r requirements.txt

script:
  - ansible-playbook -v ansible/site.yml -i ansible/dev -b
  - tox

after_success:
  - caveralls