sudo: required
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get update
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo echo "y" | sudo dpkg --force-depends -i wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo apt-get install -f

install:
  - pip install ansible
  - pip install -r requirements.txt

script:
  - echo $(which python3)
  - ansible-playbook ansible/site.yml --syntax-check
  - ansible-playbook ansible/site.yml --skip-tags python -vv
  - tox

after_success:
  - caveralls