sudo: required
language: python
python:
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3.6
  - pip install ansible

install:
  - pip install -r requirements.txt

script:
  - ansible-playbook -v ansible/site.yml -i ansible/dev -b
  - tox

after_success:
  - caveralls