language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt


before_script:
  - sudo bash ./travis/before-script.sh

script:
  - tox
  - coverage run -m pytest tests/
  - coverage report -m

after_success:
  - caveralls