"""Test

Revision ID: 8672c7e7443d
Revises: 
Create Date: 2018-07-13 18:41:27.248718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8672c7e7443d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('daevoo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('dell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('dynex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('grundic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('horizont',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('lg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('manta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('panasonic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('philips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('samsung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('sharp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('shinco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('shivaki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('sony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('supra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('telefunken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('tomson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('toshiba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vityaz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('power', sa.String(length=120), nullable=True),
    sa.Column('t_con', sa.String(length=120), nullable=True),
    sa.Column('x_main', sa.String(length=120), nullable=True),
    sa.Column('y_main', sa.String(length=120), nullable=True),
    sa.Column('logic', sa.String(length=120), nullable=True),
    sa.Column('invertor', sa.String(length=120), nullable=True),
    sa.Column('y_scan', sa.String(length=120), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vityaz')
    op.drop_table('user')
    op.drop_table('toshiba')
    op.drop_table('tomson')
    op.drop_table('telefunken')
    op.drop_table('supra')
    op.drop_table('sony')
    op.drop_table('shivaki')
    op.drop_table('shinco')
    op.drop_table('sharp')
    op.drop_table('samsung')
    op.drop_table('philips')
    op.drop_table('panasonic')
    op.drop_table('manta')
    op.drop_table('lg')
    op.drop_table('horizont')
    op.drop_table('grundic')
    op.drop_table('dynex')
    op.drop_table('dell')
    op.drop_table('daevoo')
    op.drop_table('bbk')
    # ### end Alembic commands ###
