- name: Check that the /usr/bin/python3.6 exists
  stat:
    path: /usr/bin/python3.6
  tags: python
  register: python_result

- name: Update apt-cache
  apt: update_cache=yes
  tags: packages, python
  when: python_result.stat.exists == False

- name: Install packages needed for installing Python
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: install python3.6
  become: yes
  apt:
    name: python3.6
    update_cache: yes


- name: Install common packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - git
    - virtualenv
    - python3-pip
    - postgresql
    - libpq-dev
    - postgresql-contrib
    - python3-psycopg2
    - build-essential

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x trusty main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become: yes
  apt:
    name: nodejs
    state: present

- name: install pip requirements
  pip:
    requirements: "{{ PROJECT_DIR }}/requirements.txt"
    virtualenv: "{{ ENV_PATH }}"
    virtualenv_python: python3.6
#
#- name: Install packages from package.json
#  shell:
#    path: /home/test/teleplata/static/

#- name: Collect statics with webpack
#  shell: npm install && npm run dev
#  args:
#    chdir: /home/test/teleplata/static

- name: Install wkhtmltopdf
  become: yes
  apt:
    deb: 'https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb'
    install_recommends: yes


- name: Collect statics with webpack
  become: yes
  npm: path=/home/test/teleplata/static executable=/usr/bin/npm

