- name: clone repository
  git:
    repo: '{{ REPO_URL }}'
    dest: '{{ PROJECT_DIR }}'
    depth: 1
    update: no

- name: Install packages for production enviroment
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx

#configure nginx
#- name: copy the nginx config file and restart
#  become: yes
#  copy:
#    src: '{{ PROJECT_DIR }}/instance/nginx.conf'
#    dest: /etc/nginx/sites-available/tele.conf
#    remote_src: yes
#    mode: preserve

- name: copy nginx config
  become: yes
  template: src=nginx.j2 dest=/etc/nginx/sites-available/tele.conf
  notify:
    - restart nginx

- name: create symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/tele.conf
    dest: /etc/nginx/sites-enabled/default
    state: link


- name: configure systemd for application
  become: yes
  template: src=teleplata.service.j2 dest=/etc/systemd/system/teleplata.service
  notify:
    - restart teleplata.service
